# fly.toml app configuration file generated for nexus-main on 2026-02-08T23:05:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nexus-main'
primary_region = 'jnb'

[build]

[[services]]
  internal_port = 5555
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 5555

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
