# fly.toml for TIM NEXUS (MASTER SSL CONFIG)
app = 'nexus-main'
primary_region = 'jnb'

[build]

[[services]]
  internal_port = 10000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 443
    # TLS handler makes this work on the Shared IPv4!
    handlers = ["tls"]

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
